<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [1]:
import numpy as np
import random

array_unidimensional = np.array([0,1,2,3,4,5,6,7,8,9])
array_unidimensional

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [2]:
array_unidimensional = np.random.randint(1,10, (10))
print(array_unidimensional)

array_bidimensional = np.reshape(array_unidimensional, (2,5))
array_bidimensional


[5 9 4 4 2 2 4 9 1 8]


array([[5, 9, 4, 4, 2],
       [2, 4, 9, 1, 8]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [3]:
array = np.array([0, 2, 0, 3, 0, 4, 0])
np.where(array != 0)[0]

array([1, 3, 5])

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [4]:
array = np.random.randint(0,1, (3,3))
array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [5]:
array = np.random.randint(1,10,10)
print(array)

print(f"El máximo es: {np.max(array)}")

print(f"El mínimo es: {np.min(array)}")

[1 7 1 4 2 8 5 3 1 1]
El máximo es: 8
El mínimo es: 1


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [6]:
array = np.random.randint(1,10,10)
print(array)

np.transpose(array)

[2 5 4 8 3 7 8 3 8 9]


array([2, 5, 4, 8, 3, 7, 8, 3, 8, 9])


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [7]:
array = np.random.randint(1,24, (2,3,4))
print(array)
print("\n")

try:
    primer15 = array[array == 15][0]
except:
    pass

print(f"El primer 15 del array: \n {primer15} \n")

print(f"Todos los elementos del primer array: \n {array[0]} \n")

print(f"La última fila del último array: \n {array[1,2]}")


[[[21  9 11 15]
  [ 9  7  4  8]
  [12 10  6  1]]

 [[15  2 18  1]
  [16 21 23 11]
  [22 18  8 13]]]


El primer 15 del array: 
 15 

Todos los elementos del primer array: 
 [[21  9 11 15]
 [ 9  7  4  8]
 [12 10  6  1]] 

La última fila del último array: 
 [22 18  8 13]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [8]:
array = np.random.randint(1,30, (3,2,5))
print(array)
print("\n")

print(f"Subarray que contiene los dos primeros elementos de cada fila del primer array : \n {array[0,:2,:2]} \n")

print(f"Subarray que contiene todas las filas de los últimos dos arrays : \n {array[1:,:,:]} \n")

[[[25  8 11 16 18]
  [25 13 20 27 14]]

 [[ 5  7 21  6  3]
  [ 3 10 28 29 25]]

 [[ 2 12  7  9 23]
  [25 13  9  5  6]]]


Subarray que contiene los dos primeros elementos de cada fila del primer array : 
 [[25  8]
 [25 13]] 

Subarray que contiene todas las filas de los últimos dos arrays : 
 [[[ 5  7 21  6  3]
  [ 3 10 28 29 25]]

 [[ 2 12  7  9 23]
  [25 13  9  5  6]]] 



#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [9]:
array = np.random.randint(1,24, (4,3,2))
print(array)


print("\n Cambio elementos de la segunda fila del segundo array por 0: \n")
array[1,:,1] = 0
print(array)
print("\n")

print("\n Cambio todos los valores del último array a -1: \n")
array[3,:,:] = -1
print(array)


[[[ 1 15]
  [14 22]
  [14  2]]

 [[10 22]
  [23 16]
  [ 3 13]]

 [[ 2 20]
  [22 18]
  [11 16]]

 [[ 2 21]
  [18 16]
  [14  5]]]

 Cambio elementos de la segunda fila del segundo array por 0: 

[[[ 1 15]
  [14 22]
  [14  2]]

 [[10  0]
  [23  0]
  [ 3  0]]

 [[ 2 20]
  [22 18]
  [11 16]]

 [[ 2 21]
  [18 16]
  [14  5]]]



 Cambio todos los valores del último array a -1: 

[[[ 1 15]
  [14 22]
  [14  2]]

 [[10  0]
  [23  0]
  [ 3  0]]

 [[ 2 20]
  [22 18]
  [11 16]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [10]:
array = np.random.randint(-10,13, (2,4,3))
print(array)

print("\n Selecciono los elementos mayores a 5: \n")
print(array[array > 5])

print("\n Reemplazo los elementos negativos por 0: \n")
array[array < 0] = 0
print(array)


[[[  2  -6  12]
  [  2   6  -9]
  [  1  -4  11]
  [ -7   3  12]]

 [[ -7  11  10]
  [ -2  -5  -3]
  [ -8  12 -10]
  [ 11   6   6]]]

 Selecciono los elementos mayores a 5: 

[12  6 11 12 11 10 12 11  6  6]

 Reemplazo los elementos negativos por 0: 

[[[ 2  0 12]
  [ 2  6  0]
  [ 1  0 11]
  [ 0  3 12]]

 [[ 0 11 10]
  [ 0  0  0]
  [ 0 12  0]
  [11  6  6]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [11]:
array = np.random.randint(1,27, (3,3,3))
print(array)

print("\n Selecciono el subarray del segundo array que contenga sóla las dos primeras columnas \n")
print(array[1,:,:2])

print("\n Selecciono todos los elementos mayores a 20 del tercer array: \n")
print(array[2, :, :][array[2, :, :] > 20])



[[[26  6 17]
  [ 8 10 26]
  [25  8 13]]

 [[26  4  3]
  [11  1 19]
  [ 3  1 14]]

 [[25 11  2]
  [14  1 13]
  [10 12 22]]]

 Selecciono el subarray del segundo array que contenga sóla las dos primeras columnas 

[[26  4]
 [11  1]
 [ 3  1]]

 Selecciono todos los elementos mayores a 20 del tercer array: 

[25 22]


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [12]:
array = np.random.randint(1,10, (10))
print(array)

print("\n Reemplazo los valores máximos y mínimos por 0: \n")

indice_max = np.where(array == np.max(array))[0] #busco índice primero
indice_min = np.where(array == np.min(array))[0]

array[indice_max] = 0 #y sustituyo
array[indice_min] = 0

print(array)



[1 3 8 3 1 7 6 1 1 1]

 Reemplazo los valores máximos y mínimos por 0: 

[0 3 0 3 0 7 6 0 0 0]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [13]:
array = np.random.randint(1,100, (15))
print(array)
print(f"El array ordenado de manera ascendente es {np.sort(array)}")


[90 68 42 31 72 60 66 96 90 83 12 10 25 59 55]
El array ordenado de manera ascendente es [10 12 25 31 42 55 59 60 66 68 72 83 90 90 96]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [14]:
array = np.random.randint(1,20, (4,4))
print(array)

print(f"\n El array con la suma de los elementos a lo largo de las columnas es")
print(np.sum(array, axis = 0))

print(f"\n El array con la suma de los elementos a lo largo de las filas es")
print(np.sum(array, axis = 1))

[[15  7 11 10]
 [ 6 10 12 12]
 [ 4  7 13 17]
 [ 1 14  7 10]]

 El array con la suma de los elementos a lo largo de las columnas es
[26 38 43 49]

 El array con la suma de los elementos a lo largo de las filas es
[43 40 41 32]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [15]:
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [16]:
array = np.random.randint(1,20, (10))
print(array)

print(f"\n La desviación estándar del array es {np.mean(array)}")
print(f"La desviación estándar del array es {round(np.std(array),2)}")

[18  4 17 18 10 19 14 11 17 14]

 La desviación estándar del array es 14.2
La desviación estándar del array es 4.47


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [17]:
array = np.random.randint(1,24, (2,3,4))
print(array)

np.transpose(array, (2,1,0))
print(f"\n El array transpuesto es: \n {array}")

[[[ 6 12 21  2]
  [ 6 10  4 23]
  [ 7 13  6 19]]

 [[ 7  2 22 20]
  [11 23 23 18]
  [ 7  5 12  4]]]

 El array transpuesto es: 
 [[[ 6 12 21  2]
  [ 6 10  4 23]
  [ 7 13  6 19]]

 [[ 7  2 22 20]
  [11 23 23 18]
  [ 7  5 12  4]]]


Método para transponer: cambia los ejes de la matriz con la sintaxis (matriz,fila,columna)

0    1    2     Índices originales

2 x  3 x  4     Array original
4 x  3 x  2     Array nuevo

2    1    0     Nuevos índices

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


0    1    2     Índices originales

3 x  4 x  2     Array original
4 x  3 x  2     Array nuevo

1    0    2     Nuevos índices

In [18]:
array = np.random.randint(1,24, (3,4,2))
print(array)

np.transpose(array, (1,0,2))
print(f"\n El array transpuesto es: \n {array}")

[[[22  6]
  [14 20]
  [13 14]
  [16 15]]

 [[ 6  4]
  [ 4  8]
  [19 11]
  [ 9 16]]

 [[18 20]
  [ 9  7]
  [11 23]
  [14  8]]]

 El array transpuesto es: 
 [[[22  6]
  [14 20]
  [13 14]
  [16 15]]

 [[ 6  4]
  [ 4  8]
  [19 11]
  [ 9 16]]

 [[18 20]
  [ 9  7]
  [11 23]
  [14  8]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


0    1    2     Índices originales

3 x  2 x  4     Array original
4 x  3 x  2     Array nuevo

2    0    1     Nuevos índices

In [19]:
array = np.random.randint(1,24, (3,2,4))
print(array)

np.transpose(array, (2,0,1))
print(f"\n El array transpuesto es: \n {array}")

[[[ 5 13  2  4]
  [ 7 14 16 10]]

 [[12  7  3  9]
  [ 2  6 21  4]]

 [[ 6 16 23  5]
  [20 10  7  1]]]

 El array transpuesto es: 
 [[[ 5 13  2  4]
  [ 7 14 16 10]]

 [[12  7  3  9]
  [ 2  6 21  4]]

 [[ 6 16 23  5]
  [20 10  7  1]]]


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [20]:
array = np.random.randint(-10,10, (3,4,5))
print(array)

array_vacio = np.empty((3,4,5), dtype = str)

print("\n")

median = np.median(array)
max = np.max(array)
min = np.min(array)

print(f"La mediana es {median} \n")

array_vacio[array == median] = "M"
array_vacio[array == max] = "MAX"
array_vacio[array == min] = "MIN"
array_vacio[array > median] = "X"
array_vacio[array < median] = "Y"

print(array_vacio)

[[[ 7  2 -2 -8  4]
  [ 8 -9  7 -7  7]
  [-8  2 -1 -1  2]
  [ 9 -2 -4 -7 -5]]

 [[ 2  0  9  6  5]
  [ 2 -6  9  8 -5]
  [-3 -7 -1  8  2]
  [ 3 -4 -2  3 -4]]

 [[-3  1  0 -4 -9]
  [-5  7 -9  2 -5]
  [-7 -5  1  4 -6]
  [ 3 -4  6  0  5]]]


La mediana es 0.0 

[[['X' 'X' 'Y' 'Y' 'X']
  ['X' 'Y' 'X' 'Y' 'X']
  ['Y' 'X' 'Y' 'Y' 'X']
  ['X' 'Y' 'Y' 'Y' 'Y']]

 [['X' 'M' 'X' 'X' 'X']
  ['X' 'Y' 'X' 'X' 'Y']
  ['Y' 'Y' 'Y' 'X' 'X']
  ['X' 'Y' 'Y' 'X' 'Y']]

 [['Y' 'X' 'M' 'Y' 'Y']
  ['Y' 'X' 'Y' 'X' 'Y']
  ['Y' 'Y' 'X' 'X' 'Y']
  ['X' 'Y' 'X' 'M' 'X']]]


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [23]:
array = np.random.randint(-10, 10, (4, 4))
print(array)

found = False
for i in range(4): #fila

    for j in range(4): #columna
        fila_columna_found = True

        for k in range(4): #comparo fila i y columna j
            if array[i][k] != array[k][j]:
                fila_columna_found = False #no coinciden
                break

        if fila_columna_found:
            found = True
            print(f"Hay una fila igual a una columna en fila {i} columna {j}")
            break

if not found:
    print("\n No hay filas y columnas iguales")


[[  5   5 -10  -8]
 [  0   3  -4   2]
 [  2   9   5   7]
 [  0  -7   2   4]]

 No hay filas y columnas iguales
