<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [158]:
import numpy as np
import random

array_unidimensional = np.array([0,1,2,3,4,5,6,7,8,9])
array_unidimensional

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [157]:
array_unidimensional = np.random.randint(1,10, (10))
print(array_unidimensional)

array_bidimensional = np.reshape(array_unidimensional, (2,5))
array_bidimensional


[5 4 1 9 1 3 6 4 6 6]


array([[5, 4, 1, 9, 1],
       [3, 6, 4, 6, 6]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [160]:
array = np.array([0, 2, 0, 3, 0, 4, 0])
np.where(array != 0)[0]

array([1, 3, 5])

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [47]:
array = np.random.randint(0,1, (3,3))
array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [168]:
array = np.random.randint(1,10,10)
print(array)

print(f"El máximo es: {np.max(array)}")

print(f"El mínimo es: {np.min(array)}")

[5 5 6 2 9 5 6 2 2 8]
El máximo es: 9
El mínimo es: 2


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [37]:
array = np.random.randint(1,10,10)
print(array)

np.transpose(array)

[1 6 4 2 7 1 2 2 6 4]


array([1, 6, 4, 2, 7, 1, 2, 2, 6, 4])


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [109]:
array = np.random.randint(1,24, (2,3,4))
print(array)
print("\n")

try:
    primer15 = array[array == 15][0]
except:
    pass

print(f"El primer 15 del array: \n {primer15} \n")

print(f"Todos los elementos del primer array: \n {array[0]} \n")

print(f"La última fila del último array: \n {array[1,2]}")


[[[11 17 10 15]
  [15 20 17 18]
  [15 13 14 15]]

 [[17 15  1  9]
  [ 5 10  3 21]
  [17 10  8  9]]]


El primer 15 del array: 
 15 

Todos los elementos del primer array: 
 [[11 17 10 15]
 [15 20 17 18]
 [15 13 14 15]] 

La última fila del último array: 
 [17 10  8  9]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [64]:
array = np.random.randint(1,30, (3,2,5))
print(array)
print("\n")

print(f"Subarray que contiene los dos primeros elementos de cada fila del primer array : \n {array[0,:2,:2]} \n")

print(f"Subarray que contiene todas las filas de los últimos dos arrays : \n {array[1:,:,:]} \n")

[[[ 8 14 28 24 23]
  [ 9 21 21 24 14]]

 [[24 23 20 19 22]
  [15 14 19 13 20]]

 [[18  4  9 17 20]
  [26  5 29 21  1]]]


Subarray que contiene los dos primeros elementos de cada fila del primer array : 
 [[ 8 14]
 [ 9 21]] 

Subarray que contiene todas las filas de los últimos dos arrays : 
 [[[24 23 20 19 22]
  [15 14 19 13 20]]

 [[18  4  9 17 20]
  [26  5 29 21  1]]] 



#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [141]:
array = np.random.randint(1,24, (4,3,2))
print(array)


print("\n Cambio elementos de la segunda fila del segundo array por 0: \n")
array[1,:,1] = 0
print(array)
print("\n")

print("\n Cambio todos los valores del último array a -1: \n")
array[3,:,:] = -1
print(array)


[[[12 18]
  [ 1 12]
  [19  3]]

 [[ 2 21]
  [ 9 17]
  [17 15]]

 [[12 13]
  [13 23]
  [23  7]]

 [[ 2  1]
  [ 3 21]
  [ 2 10]]]

 Cambio elementos de la segunda fila del segundo array por 0 

[[[12 18]
  [ 1 12]
  [19  3]]

 [[ 2  0]
  [ 9  0]
  [17  0]]

 [[12 13]
  [13 23]
  [23  7]]

 [[ 2  1]
  [ 3 21]
  [ 2 10]]]



 Cambio todos los valores del último array a -1 

[[[12 18]
  [ 1 12]
  [19  3]]

 [[ 2  0]
  [ 9  0]
  [17  0]]

 [[12 13]
  [13 23]
  [23  7]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [145]:
array = np.random.randint(-10,13, (2,4,3))
print(array)

print("\n Selecciono los elementos mayores a 5: \n")
print(array[array > 5])

print("\n Reemplazo los elementos negativos por 0: \n")
array[array < 0] = 0
print(array)


[[[ 5 12  4]
  [ 3  9  3]
  [ 4  7  2]
  [11 -5  5]]

 [[ 1 12  4]
  [-9 12  2]
  [-4 12  0]
  [ 6  5 -8]]]

 Selecciono los elementos mayores a 5: 

[12  9  7 11 12 12 12  6]

 Reemplazo los elementos negativos por 0: 

[[[ 5 12  4]
  [ 3  9  3]
  [ 4  7  2]
  [11  0  5]]

 [[ 1 12  4]
  [ 0 12  2]
  [ 0 12  0]
  [ 6  5  0]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [175]:
array = np.random.randint(1,27, (3,3,3))
print(array)

print("\n Selecciono el subarray del segundo array que contenga sóla las dos primeras columnas \n")
print(array[1,:,:2])

print("\n Selecciono todos los elementos mayores a 20 del tercer array: \n")
print(array[2, :, :][array[2, :, :] > 20])



[[[ 1 23  8]
  [11  6 10]
  [20 12  2]]

 [[21 13  4]
  [26  9 22]
  [10 11 22]]

 [[22 24 24]
  [ 3  3 22]
  [16 17 26]]]

 Selecciono el subarray del segundo array que contenga sóla las dos primeras columnas 

[[21 13]
 [26  9]
 [10 11]]

 Selecciono todos los elementos mayores a 20 del tercer array: 

[22 24 24 22 26]


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [253]:
array = np.random.randint(1,10, (10))
print(array)

print("\n Reemplazo los valores máximos y mínimos por 0: \n")

indice_max = np.where(array == np.max(array))[0] #busco índice primero
indice_min = np.where(array == np.min(array))[0]

array[indice_max] = 0 #y sustituyo
array[indice_min] = 0

print(array)



[8 1 3 1 7 8 6 1 4 5]

 Reemplazo los valores máximos y mínimos por 0: 

[0 0 3 0 7 0 6 0 4 5]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [197]:
array = np.random.randint(1,100, (15))
print(array)
print(f"El array ordenado de manera ascendente es {np.sort(array)}")


[86  3 13 75 83 99 83 68 84 47 47 36 85 37 78]
El array ordenado de manera ascendente es [ 3 13 36 37 47 47 68 75 78 83 83 84 85 86 99]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [203]:
array = np.random.randint(1,20, (4,4))
print(array)

print(f"\n El array con la suma de los elementos a lo largo de las columnas es")
print(np.sum(array, axis = 0))

print(f"\n El array con la suma de los elementos a lo largo de las filas es")
print(np.sum(array, axis = 1))

[[19 13  8  5]
 [15 10  2  9]
 [16 14 11 11]
 [15 16  3 18]]

 El array con la suma de los elementos a lo largo de las columnas es
[65 53 24 43]

 El array con la suma de los elementos a lo largo de las filas es
[45 36 52 52]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [215]:
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [207]:
array = np.random.randint(1,20, (10))
print(array)

print(f"\n La desviación estándar del array es {np.mean(array)}")
print(f"La desviación estándar del array es {round(np.std(array),2)}")

[17 15 13  5 10 18  4 13  2  5]

 La desviación estándar del array es 10.2
La desviación estándar del array es 5.53


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [222]:
array = np.random.randint(1,24, (2,3,4))
print(array)

np.transpose(array, (2,1,0))
print(f"\n El array transpuesto es: \n {array}")

[[[ 1 17  6 17]
  [ 5  9  8  3]
  [23  3 16  2]]

 [[ 5 13 11  4]
  [17  2  9 11]
  [15  1  5 23]]]

 El array transpuesto es: 
 [[[ 1 17  6 17]
  [ 5  9  8  3]
  [23  3 16  2]]

 [[ 5 13 11  4]
  [17  2  9 11]
  [15  1  5 23]]]


Método para transponer: cambia los ejes de la matriz con la sintaxis (matriz,fila,columna)

0    1    2     Índices originales

2 x  3 x  4     Array original
4 x  3 x  2     Array nuevo

2    1    0     Nuevos índices

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


0    1    2     Índices originales

3 x  4 x  2     Array original
4 x  3 x  2     Array nuevo

1    0    2     Nuevos índices

In [223]:
array = np.random.randint(1,24, (3,4,2))
print(array)

np.transpose(array, (1,0,2))
print(f"\n El array transpuesto es: \n {array}")

[[[ 2  6]
  [13 11]
  [ 6 12]
  [21  9]]

 [[ 5  7]
  [13 11]
  [21 18]
  [ 8  2]]

 [[16 14]
  [17 17]
  [ 9 14]
  [10 14]]]

 El array transpuesto es: 
 [[[ 2  6]
  [13 11]
  [ 6 12]
  [21  9]]

 [[ 5  7]
  [13 11]
  [21 18]
  [ 8  2]]

 [[16 14]
  [17 17]
  [ 9 14]
  [10 14]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


0    1    2     Índices originales

3 x  2 x  4     Array original
4 x  3 x  2     Array nuevo

2    0    1     Nuevos índices

In [227]:
array = np.random.randint(1,24, (3,2,4))
print(array)

np.transpose(array, (2,0,1))
print(f"\n El array transpuesto es: \n {array}")

[[[ 1  9  1  3]
  [21 23 11  5]]

 [[ 8 21 15 12]
  [ 4 23  9  6]]

 [[ 6  3  6 10]
  [ 9 21 17  5]]]

 El array transpuesto es: 
 [[[ 1  9  1  3]
  [21 23 11  5]]

 [[ 8 21 15 12]
  [ 4 23  9  6]]

 [[ 6  3  6 10]
  [ 9 21 17  5]]]


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [262]:
array = np.random.randint(-10,10, (3,4,5))
print(array)

array_vacio = np.empty((3,4,5), dtype = str)

print("\n")

median = np.median(array)
max = np.max(array)
min = np.min(array)

print(f"La mediana es {median} \n")

array_vacio[array == median] = "M"
array_vacio[array == max] = "MAX"
array_vacio[array == min] = "MIN"
array_vacio[array > median] = "X"
array_vacio[array < median] = "Y"

print(array_vacio)

[[[  3   0  -4   2  -7]
  [  9   7  -3  -6  -1]
  [  1  -2  -7 -10   0]
  [  4  -3   2   8  -3]]

 [[ -2 -10   7 -10  -1]
  [  9  -2   3  -1 -10]
  [ -3  -2   4  -7   1]
  [  3  -7   1   1   0]]

 [[ -7  -6  -1   8  -4]
  [ -9  -1   9  -5   6]
  [ -8  -8   5  -4   0]
  [  3   0   0  -3  -7]]]


La mediana es -1.0 

[[['X' 'X' 'Y' 'X' 'Y']
  ['X' 'X' 'Y' 'Y' 'M']
  ['X' 'Y' 'Y' 'Y' 'X']
  ['X' 'Y' 'X' 'X' 'Y']]

 [['Y' 'Y' 'X' 'Y' 'M']
  ['X' 'Y' 'X' 'M' 'Y']
  ['Y' 'Y' 'X' 'Y' 'X']
  ['X' 'Y' 'X' 'X' 'X']]

 [['Y' 'Y' 'M' 'X' 'Y']
  ['Y' 'M' 'X' 'Y' 'X']
  ['Y' 'Y' 'X' 'Y' 'X']
  ['X' 'X' 'X' 'Y' 'Y']]]


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [290]:
array = np.random.randint(-10, 10, (4, 4))
print(array)

found = False
for i in range(4):
    for j in range(4):
        fila_columna_found = True
        for k in range(4):
            if array[i][k] == array[i][k]:
                fila_columna_found = False
                break
        if fila_columna_found:
            print(f"Hay una fila igual a una columna en {[i][k]}")
            found = True
            break
if not found:
    print("\n No hay filas y columnas iguales")
    

[[  7  -2  -8   5]
 [-10  -7   5   2]
 [ -5   5  -5   4]
 [ -9  -1   3  -3]]

 No hay filas y columnas iguales
